src/Entity/Topicality.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TopicalityRepository")
 */
class Topicality
{
    function __construct()
    {
        $this->created_at = new \DateTime();
        $this->topicComments = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $topic_title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $topic_owner;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $topic_text;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TopicComment", mappedBy="topic", orphanRemoval=true)
     */
    private $topicComments;

    public function getSlug():string{
        return (new Slugify())->slugify($this->topic_title);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTopicTitle(): ?string
    {
        return $this->topic_title;
    }

    public function setTopicTitle(string $topic_title): self
    {
        $this->topic_title = $topic_title;

        return $this;
    }

    public function getTopicOwner(): ?string
    {
        return $this->topic_owner;
    }

    public function setTopicOwner(string $topic_owner): self
    {
        $this->topic_owner = $topic_owner;

        return $this;
    }

    public function getTopicText(): ?string
    {
        return $this->topic_text;
    }

    public function setTopicText(string $topic_text): self
    {
        $this->topic_text = $topic_text;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|TopicComment[]
     */
    public function getTopicComments(): Collection
    {
        return $this->topicComments;
    }

    public function addTopicComment(TopicComment $topicComment): self
    {
        if (!$this->topicComments->contains($topicComment)) {
            $this->topicComments[] = $topicComment;
            $topicComment->setTopic($this);
        }

        return $this;
    }

    public function removeTopicComment(TopicComment $topicComment): self
    {
        if ($this->topicComments->contains($topicComment)) {
            $this->topicComments->removeElement($topicComment);
            // set the owning side to null (unless already changed)
            if ($topicComment->getTopic() === $this) {
                $topicComment->setTopic(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields = "email", message= "Votre email est déjà utilisé, Veillez vous connecter")
 */
class User implements UserInterface,\Serializable
{
    function __construct()
    {
        $this->created_at = new \DateTime();
        $this->topicComments = new ArrayCollection();
        $this->videoComments = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $no_order;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $speciality;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TopicComment", mappedBy="user", orphanRemoval=true)
     */
    private $topicComments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\VideoComment", mappedBy="user", orphanRemoval=true)
     */
    private $videoComments;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getcountry(): ?string
    {
        return $this->country;
    }

    public function setcountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getNoOrder(): ?string
    {
        return $this->no_order;
    }

    public function setNoOrder(string $no_order): self
    {
        $this->no_order = $no_order;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSpeciality(): ?string
    {
        return $this->speciality;
    }

    public function setSpeciality(string $speciality): self
    {
        $this->speciality = $speciality;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|TopicComment[]
     */
    public function getTopicComments(): Collection
    {
        return $this->topicComments;
    }

    public function addTopicComment(TopicComment $topicComment): self
    {
        if (!$this->topicComments->contains($topicComment)) {
            $this->topicComments[] = $topicComment;
            $topicComment->setUser($this);
        }

        return $this;
    }

    public function removeTopicComment(TopicComment $topicComment): self
    {
        if ($this->topicComments->contains($topicComment)) {
            $this->topicComments->removeElement($topicComment);
            // set the owning side to null (unless already changed)
            if ($topicComment->getUser() === $this) {
                $topicComment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|VideoComment[]
     */
    public function getVideoComments(): Collection
    {
        return $this->videoComments;
    }

    public function addVideoComment(VideoComment $videoComment): self
    {
        if (!$this->videoComments->contains($videoComment)) {
            $this->videoComments[] = $videoComment;
            $videoComment->setUser($this);
        }

        return $this;
    }

    public function removeVideoComment(VideoComment $videoComment): self
    {
        if ($this->videoComments->contains($videoComment)) {
            $this->videoComments->removeElement($videoComment);
            // set the owning side to null (unless already changed)
            if ($videoComment->getUser() === $this) {
                $videoComment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * String representation of object
     * @link https://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        return serialize([$this->id,
                        $this->first_name,
                        $this->last_name,
                        $this->country,
                        $this->email,
                        $this->phone_number,
                        $this->postal_code,
                        $this->speciality,
                        $this->no_order,
                        $this->password,
                        $this->created_at]);
    }

    /**
     * Constructs the object
     * @link https://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        list($this->id,
            $this->first_name,
            $this->last_name,
            $this->country,
            $this->email,
            $this->phone_number,
            $this->postal_code,
            $this->speciality,
            $this->no_order,
            $this->password,
            $this->created_at) = unserialize($serialized);
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return array('ROLE_USER');
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return ["ROLE_USER"];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

templates/components/_bigActualite.html.twig
<div class="card mt-4" style="width: 80%">
    <div class="card-body">
        <h5 class="card-title">{{ topic.topicTitle }}</h5>
        <p class="card-text ">{{ topic.topicText|slice(1,300) ~ "..." }}</p>
    </div>

    <div class="card-body">
        <a href="{{ path("actualiteDetail",{slug:topic.slug,id:topic.id}) }}" class="card-link">Voir</a>
    </div>
    <footer class="blockquote-footer">
        <small class="text-muted">
            Créé par {{ topic.topicOwner }} le <cite title="Source Title">{{ topic.createdAt.format('d-m-Y à H:i:s') }}</cite>
        </small>
    </footer>

</div>

templates/components/_bigVideo.html.twig
<div class="card" style="width: 80%">
    <img class="card-img-top" src="{{ video.photo1}}" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">{{ video.name }}</h5>
        <p class="card-text ">{{ video.description|slice(1,300) ~ "..." }}</p>
    </div>

    <div class="card-body">
        <a href="{{ path("videoDetail",{slug:video.slug,id:video.id}) }}" class="card-link">Voir</a>
    </div>
    <footer class="blockquote-footer">
        <small class="text-muted">
            Créé le  <cite title="Source Title">{{ video.createdAt.format('d-m-Y à H:i:s') }}</cite>
        </small>
    </footer>

</div>

templates/components/_mediumActualite.twig
{#<div class="card" style="width: 18rem;">#}
    {#<div class="card-body">#}
        {#<h5 class="card-title">{{ topic.topicTitle }}</h5>#}
        {#<p class="card-text ">{{ topic.topicText|slice(1,random([200,100,150,50])) ~ "..." }}</p>#}
    {#</div>#}

    {#<div class="card-body">#}
        {#<a href="{{ path("actualiteDetail",{slug:topic.slug,id:topic.id}) }}" class="card-link">Voir</a>#}
    {#</div>#}
    {#<footer class="blockquote-footer">#}
        {#<small class="text-muted">#}
            {#Créé par {{ topic.topicOwner }} le <cite title="Source Title">{{ topic.createdAt.format('d-m-Y à H:i:s') }}</cite>#}
        {#</small>#}
    {#</footer>#}

{#</div>#}

<div class="single-blog-area col-sm-5 shadow" style="margin: 10px" >
    <!-- Post Thumbnail -->
    <div class="blog-post-thumbnail ">
        {#<img src="{{ video.photo1}}" alt="">#}
        <!-- Post Date -->
        <div class="post-date">
            <a href="#">{{ topic.createdAt.format('M d, Y') }}</a>
        </div>
    </div>
    <!-- Post Content -->
    <div class="post-content">
        <div class="post-author">
            <a href="{{ path("actualiteDetail",{slug:topic.slug,id:topic.id}) }}"> <span class="plus">+</span></a>
        </div>
        <a href="#" class="headline mb-0">{{ topic.topicTitle }}</a>
        <div class="post-meta">
            <a href="{{ path("actualiteDetail",{slug:topic.slug,id:topic.id}) }}"class="post-author-name">par Dr. {{ topic.topicOwner }}</a> | <a href="#" class="post-catagory">Dental</a>
        </div>
        <p>{{ path("actualiteDetail",{slug:topic.slug,id:topic.id}) }}</p>
    </div>

</div>

templates/components/_mediumVideo.html.twig
{#<div class="card" style="width: 18rem;">#}
    {#<img class="card-img-top" src="" alt="Card image cap">#}
    {#<div class="card-body">#}
        {#<h5 class="card-title">{{ video.name }}</h5>#}
        {#<p class="card-text ">{{ video.description|slice(1,random([100,50,75,25])) ~ "..." }}</p>#}
    {#</div>#}

    {#<div class="card-body">#}
        {#<a href="{{ path("videoDetail",{slug:video.slug,id:video.id}) }}" class="card-link">Voir</a>#}
    {#</div>#}
    {#<footer class="blockquote-footer">#}
        {#<small class="text-muted">#}
            {#Créé le  <cite title="Source Title">{{ video.createdAt.format('d-m-Y à H:i:s') }}</cite>#}
        {#</small>#}
    {#</footer>#}

{#</div>#}

<div class="single-blog-area col-sm-5 shadow" style="margin: 10px" >
    <!-- Post Thumbnail -->
    <div class="blog-post-thumbnail ">
        <img src="{{ video.photo1}}" alt="">
        <!-- Post Date -->
        <div class="post-date">
            <a href="#">{{ video.createdAt.format('M d, Y') }}</a>
        </div>
    </div>
    <!-- Post Content -->
    <div class="post-content">
        <div class="post-author">
            <a href="{{ path("videoDetail",{slug:video.slug,id:video.id}) }}"> <span class="plus">+</span></a>
        </div>
        <a href="#" class="headline mb-0">{{ video.name }} </a>
        <div class="post-meta">
            <a href="{{ path("videoDetail",{slug:video.slug,id:video.id}) }}"class="post-author-name">by Dr. Cristinne Smith</a> | <a href="#" class="post-catagory">Dental</a>
        </div>
        <p>{{ video.description|slice(1,random([100,50,75,25])) ~ "..." }}</p>
    </div>

</div>

templates/components/_smallTopic.html.twig
<div class="widget-single-blog-post d-flex align-items-center">
    <div class="widget-post-thumbnail pr-3">
        {#<img src="img/blog-img/ln1.jpg" alt="">#}
    </div>
    <div class="widget-post-content">
        <a href="{{ path("actualiteDetail",{slug:topic.slug,id:topic.id}) }}">{{ topic.topicTitle }}</a>
        <p>{{ topic.createdAt.format('M d, Y') }}</p>
    </div>
</div>

templates/components/_smallVideo.html.twig
<style>

    .mini-card{
        position: relative;
        height: 150px;
        margin-bottom: 10px;
        overflow: hidden;
    }
    .mini-card-img{
        height: 100%;
        width: 100%;
    }
    .mini-card-info{
        position: absolute;
        display: flex;
        flex-direction: row-reverse;
        justify-content: space-around;
        align-items: center;
        top: 0px;
        width: 100%;
        height: 100%;
        z-index: 3;
        opacity: 0;
        background-color: rgba(0, 108, 255,0.5);
        transition: opacity 0.5s;
    }
    .mini-card-info a{
        color: white;
    }
    .mini-card-info:hover{
        opacity:1;
    }
    .mini-card-play{
        font-size: xx-large;
        padding: 10px;
        border-radius: 40px;
        display: inline-block;
        position: relative;
        width: 50px;
        text-align: right;
        background-color: rgb(0, 108, 255);
    }
    .mini-card-play:hover
    {
        animation: play 500ms;
    }
    @keyframes play {
        from {
            transform: rotate(0deg);
        }
        to{
            transform: rotate(360deg);
        }
    }
</style>
<div class="mini-card" >

    <img src="{{ video.photo1}}" alt="" class="mini-card-img">
    <div class="mini-card-info">
        <div class="">
            <a href="{{ path("videoDetail",{slug:video.slug,id:video.id}) }}"> <i class="fa fa-play mini-card-play"></i></a>
        </div>
        <div>
            <div class="">
                <a href="#">{{ video.createdAt.format('M d, Y') }}</a>
            </div>
            <a href="#" class="">{{ video.name }} </a>
            <div class="">
                <a href="{{ path("videoDetail",{slug:video.slug,id:video.id}) }}"class="post-author-name">by Dr. Cristinne Smith</a> | <a href="#" class="post-catagory">Dental</a>
            </div>
        </div>


    </div>

</div>

templates/components/comment.html.twig
<li class="single_comment_area" >
    <div class="comment-wrapper d-flex">
        <div class="comment-content">
            <div class="comment-meta">
                <a href="#" class="comment-author-name">{{ app.user.lastName }} {{ app.user.firstName }}</a> |
                <a href="#" class="comment-date"> {{ comment.createdAt| date("M d, Y") }}</a>
            </div>
            <p>{{ comment.comment }}</p>
        </div>
    </div>
</li>